name: Construir APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Crear carpeta web
        run: |
          mkdir -p www
          cp index.html www/index.html
          cp icon-192.png www/icon-192.png
          cp icon-512.png www/icon-512.png

      - name: Instalar dependencias
        run: npm install

      - name: Agregar Android
        run: npx cap add android

      - name: Sincronizar
        run: npx cap sync

      - name: Compilar APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: que-carajos-cocino-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
